### ISSUE TITLE
Wording english on home : "transformational" too long for mobile portrait mode

### ISSUE THREAD

**Issue by silkine** [sinnerschrader/sinnerschrader-website#11]
Nice Fonts, nice site! 

![screenshot_20161118-104615](https://cloud.githubusercontent.com/assets/7026773/20425782/7d725d5a-ad7c-11e6-9152-e23149b8618e.png)

**Comment by kotzendekrabbe** [comment]
thanks a lot! we'll fix it, soon.

**Comment by silkine** [comment]
HTC One M9, Android 6.0, Chrome,  HTC sense Version 7.0

**Comment by kotzendekrabbe** [comment]
@silkine perfect - thank you :)

**Comment by KnisterPeter** [comment]
Closed by #15
