### ISSUE TITLE
about/why | Module_18_Infographik3 | wide viewports

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/sinnerschrader-website#113]
Limit the N1 SVG height to the same rules used for the second teaser on the home page.

**Actual**
![image](https://cloud.githubusercontent.com/assets/23521409/20799571/dd3f1e24-b7e2-11e6-972a-d5fac52b5707.png)
![image](https://cloud.githubusercontent.com/assets/23521409/20799577/e288ec70-b7e2-11e6-9a5d-165837400337.png)

**Intended**
![image](https://cloud.githubusercontent.com/assets/23521409/20799590/ec0b2344-b7e2-11e6-8c50-d79967f65c1b.png)

**Comment by kotzendekrabbe** [comment]
- max-height for infographic-hero (svg) modules
- background-size (max-height) for infographic background-image (something like, 80vh)

- beware of .facts list, this is the element which controls the height of the module
