### ISSUE TITLE
Redirects from old URls not working

### ISSUE THREAD

**Issue by chrjung** [sinnerschrader/sinnerschrader-website#16]
some old /en URLs lead to 404page
eg.
https://sinnerschrader.com/en/
https://sinnerschrader.com/en/agency/news/

others are redirected correctly
eg
https://sinnerschrader.com/en/careers
https://sinnerschrader.com/en/work/projects

**Comment by marionebl** [comment]
Thanks for reporting! We'll have a look at this.

**Comment by marionebl** [comment]
The appropriate redirect rules should be added to [redirects.json#L110](https://github.com/sinnerschrader/sinnerschrader-website/blob/3481e6757e821c51e27b860c503f9e745158e314/redirects.json#L110)
