### ISSUE TITLE
Replace the current navigation animation with a more subtle one

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/sinnerschrader-website#28]
The current implementation suffers from some problems I'd like to alleviate:

## Performance
Animating the height of the uppermost item in the DOM is slow and causes frame drops. Most of the time this is hidden by the fact the page is loading. For the best case where everything is delivered from cache this is jarring though.

![current-animation](https://cloud.githubusercontent.com/assets/4248851/20445552/d32431ac-add5-11e6-802f-23d0767346ee.gif)

## Page jank
We invested quite some time into [removing](https://github.com/sinnerschrader/sinnerschrader-website/commit/4db29c46f3093ee48fd517dda4e8bffa6c8e3345) all notable page jank from the site. Animating the height of a early component foils this goal. The following example is a screencapture taken from hitting `Cmd+R` when looking at a part of the page further down. The shift happens without user interaction.

![current-animation-jank](https://cloud.githubusercontent.com/assets/4248851/20445581/f09c657e-add5-11e6-9027-85465540d15e.gif)

## Proposal

Change to the following animation 

[Demo](http://s.codepen.io/marionebl/debug/ObWXNR)

![new-animation](https://cloud.githubusercontent.com/assets/4248851/20445727/941aaa8a-add6-11e6-9cf1-59082a8623ed.gif)

**Comment by Dangoo** [comment]
I'd suggest to

1. Add `z-index: 1` to `.mod-story1 ` (or remove from `mod-hero`)
2. Increase height of `.mod-hero` by value `n`
3. Use negative `margin-top` of value `n`: `margin-top: -var(--n);` for `.mod-story1`
4. Add `transform: translateY(var(--n));` to `.mod-story1` and `transition: transform 1s ease`;
5. After page load set translateY to 0.

This gives you the same effect as desired but without the whole page being moved around after rendering.

**Comment by marionebl** [comment]
Closing for now. Perhaps we should tackle this when progressively enhancing the site.
