### ISSUE TITLE
Add license(s)

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/sinnerschrader-website#32]
For the sake of clarity we should add license information to the repository.

**Comment by marionebl** [comment]
How should we go about this? Is all the source and content MIT-style free to use?

**Comment by KnisterPeter** [comment]
Thats nothing we - as the developers - could decide.

**Comment by marionebl** [comment]
For sure, who should be pulled into the loop?

**Comment by KnisterPeter** [comment]
For now lets assign to @julehen.
She should clearify this.

**Comment by hblank** [comment]
MIT license works great for us, but: we cannot open source the pictures, means: we have to exclude the "static" folder (https://github.com/sinnerschrader/sinnerschrader-website/tree/master/static). However that works ;)

**Comment by marionebl** [comment]
Some ideas: http://softwareengineering.stackexchange.com/questions/289929/how-to-handle-oss-license-on-github-with-non-oss-pictures

**Comment by hblank** [comment]
Was my first guess as well, there might be no better solution.

**Comment by KnisterPeter** [comment]
That will be hard for us to do, because this repo holds the page and is public. In that [folder](https://github.com/sinnerschrader/sinnerschrader-website/tree/master/docs) all images must reside.
We could change the process of hosting the website in a private repo but still on github-pages. That repo contains the private images and the oss parts will be merged in.
But the whole setup will get a lot more complicated.

**Comment by marionebl** [comment]
@KnisterPeter Nah, the images are public (as opposed to open-licensed) anyway, right? I'm talking about placing them under a different license and make that as explicit as possible by placing them in a different repository. Let's copy over the license file from the closed-licensed repo into dist/static, that should be enough. The top-level License file here could include an exclusion of the dist/static folder.

**Comment by KnisterPeter** [comment]
If you place them in a different repo, how does schlump know/get them and copy them over?

**Comment by marionebl** [comment]
I'd place open-licensed images on `/static/` and overwrite them with the contents of the closed repo for deployments.

**Comment by hblank** [comment]
Taking the idea from @marionebl: maybe we can ask our creatives to provide some "generic" placeholders, i.e. self-made sketches, which we can open source alongside with the code?

**Comment by marionebl** [comment]
I went ahead and

* created https://github.com/sinnerschrader/sinnerschrader-website-static, which contains all non-licensable assets
* assembled a slew of OSS stock photos for local development
* create a small pipeline from sinnerschrader/sinnerschrader-website-static to sinnerschrader/sinnerschrader-website

--
Demo Development Assets (with `npm run taint:fonts`):

**Comment by marionebl** [comment]
@hblank Could you have a quick look and give some feedback? Thanks!

**Comment by hblank** [comment]
@marionebl works great for me! looks even better than expected ;) I talked to Martin Gassner that we could/should replace these images with something uniquely crafted by S2 later, but that's not a blocker for now.

**Comment by marionebl** [comment]
🎉 We have a license!
