### ISSUE TITLE
Remove Google Analytics JavaScript

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/sinnerschrader-website#34]
I propose we remove the JavaScript for Google Analytics found at [src/templates/_layouts/_partials/head.html#L6](https://github.com/sinnerschrader/sinnerschrader-website/blob/5a5e05d1db38b3d75973c9dd8a1b9a41e63182db/src/templates/_layouts/_partials/head.html#L6) and solely rely on the `<noscript>` fallback (without the `noscript` wrapper though) at [src/templates/_layouts/standard.html#L9](https://github.com/sinnerschrader/sinnerschrader-website/blob/5a5e05d1db38b3d75973c9dd8a1b9a41e63182db/src/templates/_layouts/standard.html#L9).

* Get rid of blocking script at beginning of page
* Be consistent about the no JavaScript rule
* Reduce tracking to the parts that does not affect the user because it is the RightThingToDo™

**Comment by marionebl** [comment]
Going forward on this on our own / pulling someone in for decision-making?

**Comment by KnisterPeter** [comment]
Leave this for PO as well. @julehen will you take over?

**Comment by julehen** [comment]
I will clarify this.

**Comment by marionebl** [comment]
@julehen Any news?
