### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/sinnerschrader-website#88]
This does not look good to me: https://travis-ci.org/sinnerschrader/sinnerschrader-website/builds/179214460

If you open the 'deployment' logs in there you can see the error.
Even though travis marked the build as successful.

**Comment by marionebl** [comment]
Yep, commenting fails - will have a look at this

**Comment by marionebl** [comment]
Adressed by https://github.com/sinnerschrader/sinnerschrader-website/pull/127
